# Generated by Django 5.2.1 on 2026-06-11 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField(verbose_name='出行日期')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基础费用')),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name='库存（可报名人数）')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='报名截止时间')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_calendar', to='routes.travelroute')),
            ],
            options={
                'ordering': ['travel_date'],
                'unique_together': {('route', 'travel_date')},
            },
        ),
    ]
